### PR TITLE
Explicitly add `.resources` directory when commiting

### PR DESCRIPTION
**Pull request by mattalexander-pantheon**
This will allow it to work for new markdown documents and graphs.

### CODE REVIEW

**Comment by neenjaw** [comment]
Hey @mattalexander-pantheon, I first need to apologize that I totally missed this PR in the midst of things.  Can you give me some context about this? I can't find anything specific about github and the `.resources` directory. Can you point me towards a use-case in practice or a support document?

**Comment by mattalexander-pantheon** [comment]
Hm, I barely remember making this change. I think I probably created a new markdown document where there wasn't one before, and it didn't work until I manually created that directory first. So I automated it.

**Comment by neenjaw** [comment]
I wonder if globbing for the changes doesn't search hidden directories.

**Comment by neenjaw** [comment]
Hey @mattalexander-pantheon I think likely the problem is that using `git commit -am "message"` might not be finding your `.resources` directory for whatever reason (could be ignored in .gitignore or something), but I don't think we need to recommed adding that directory to the main README

**Comment by aakside** [comment]
I've had to do this too. Images in `.resources` are untracked and I couldn't figure out why (my .`gitignore` seems compatible).

**Comment by neenjaw** [comment]
Strange, maybe just because is a hidden direction (as it is prefixed by `.`)

**Pull request closed without merging**
