### PR TITLE
update mermaid-cli version

### PR DESCRIPTION
**Pull request by Marloxo**

### CODE REVIEW

**Comment by neenjaw** [comment]
Thanks for this PR.  Is this and @omar-binary the same person? I saw the other one first, and so I accepted that PR (#10).  Is that okay?

**Comment by omar-binary** [comment]
no worries, yeah same person @Marloxo  is my personal account,
I forget to switch my account when I sent the first PR

thank you so much for your support

**Comment by neenjaw** [comment]
Double credit then! :)

Thanks so much!

**Comment by Marloxo** [comment]
Is it possible to release and create a new tag, with the new changes,
I'm trying to pull the new version of this action, but seems it won't update to github marketplace till there is a new version.

**Comment by neenjaw** [comment]
Oh right, yes. Good catch

**Comment by neenjaw** [comment]
See release 0.2.1

**Comment by Marloxo** [comment]
@neenjaw sorry for bugging again, just noticed that `mermaid-js/mermaid-cli` is in the docker container, 
I guess we need to rebuild that image in order to get the new version of `mermaid-cli`

https://hub.docker.com/r/neenjaw/mermaid

**Comment by neenjaw** [comment]
Right again, I'll do that this morning. I'll ping you when it's done.

**Comment by neenjaw** [comment]
@Marloxo I built a pushed a new image `neenjaw/mermaid:8.7.0`

**Comment by Marloxo** [comment]
@neenjaw great! but I guess we will need to update the tag again since there is a change in dockerfile, in order to pick the new changes to marketplace

**Comment by neenjaw** [comment]
Agh, yes.

**Pull request merged**
