### PR TITLE
Accept .mmd files as mermaid files

### PR DESCRIPTION
**Pull request by hilli**
There seems to be a bit indecisiveness on the net on which extension to use for dedicated mermaid files.
Ie https://marketplace.visualstudio.com/items?itemName=tomoyukim.vscode-mermaid-editor only works on .mmd files.
This will to support that extension.

### CODE REVIEW

**Comment by neenjaw** [comment]
This sounds reasonable, could you also add the extension to the example workflows in `/README.md`?

**Comment by hilli** [comment]
I think that's was all places.

**Comment by neenjaw** [comment]
Wonderful! Thanks @hilli!

I'll merge this when I get back to my computer.

**Comment by neenjaw** [comment]
[Release Published with changes](https://github.com/neenjaw/compile-mermaid-markdown-action/releases/tag/0.2.4)

**Comment by hilli** [comment]
Awesome. Thanks for your work on this, @neenjaw!

**Pull request merged**
